# Generated by Django 3.0.2 on 2020-01-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laureat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cne', models.CharField(default='', max_length=10, unique='True')),
                ('nom', models.CharField(default='', max_length=50)),
                ('prenom', models.CharField(default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=100, unique='True')),
                ('telephone', models.CharField(blank=True, default='', max_length=12)),
                ('pdp', models.ImageField(blank=True, height_field=50, upload_to='photos', width_field=50)),
                ('situation_familial', models.CharField(default='', max_length=50)),
                ('nationalite', models.CharField(default='', max_length=50)),
                ('date_naissance', models.DateTimeField()),
                ('date_inscription', models.DateTimeField()),
                ('sexe', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
