# Generated by Django 3.0.2 on 2020-01-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laureats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laureat',
            options={'ordering': ['date_inscription']},
        ),
    ]
