# Generated by Django 3.0.2 on 2020-01-10 20:23

from django.db import migrations, models
import django.db.models.deletion
import laureats.models


class Migration(migrations.Migration):

    dependencies = [
        ('laureats', '0004_auto_20200109_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pays', models.CharField(max_length=50)),
                ('ville', models.CharField(blank=True, default='', max_length=50)),
                ('adresse', models.CharField(blank=True, default='', max_length=255)),
                ('zip_code', models.IntegerField()),
            ],
            options={
                'ordering': ['zip_code'],
            },
        ),
        migrations.AlterField(
            model_name='laureat',
            name='pdp',
            field=models.ImageField(blank=True, upload_to=laureats.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='laureat',
            name='situation_familiale',
            field=models.CharField(choices=[(1, 'Célibataire'), (2, 'Marié(e)')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='laureat',
            name='adresse',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='laureats', to='laureats.Adresse'),
            preserve_default=False,
        ),
    ]
