# Generated by Django 3.0.2 on 2020-01-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laureats', '0005_auto_20200110_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.IntegerField()),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
    ]
