# Generated by Django 3.0.2 on 2020-01-10 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laureats', '0007_laureat_filiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('laureat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laureats.Laureat')),
                ('etablissement', models.CharField(default='', max_length=100)),
                ('sujet_etude', models.CharField(default='', max_length=255)),
                ('new_date_inscription', models.DateField()),
            ],
            options={
                'ordering': ['new_date_inscription'],
            },
            bases=('laureats.laureat',),
        ),
    ]
