# Generated by Django 3.0.2 on 2020-01-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laureats', '0009_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='libelle',
            field=models.CharField(default='', max_length=255),
        ),
    ]
