# Generated by Django 3.0.2 on 2020-01-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laureats', '0010_auto_20200111_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(default='', max_length=255)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.AlterField(
            model_name='employe',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='laureats.Profession'),
        ),
    ]
